# Generated by Django 5.0 on 2024-02-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form_contact',
            new_name='Db_contact',
        ),
    ]
