# Generated by Django 5.0 on 2024-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_form_contact_db_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_contact',
            name='date_of_send',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='db_contact',
            name='readed_by_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='خوانده شده توسط ادمین'),
        ),
        migrations.AddField(
            model_name='db_contact',
            name='response_by_admin',
            field=models.TextField(null=True, verbose_name='جواب ادمین'),
        ),
    ]
