# Generated by Django 5.0 on 2024-02-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_db_contact_date_of_send_db_contact_readed_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_contact',
            name='response_by_admin',
            field=models.TextField(blank=True, null=True, verbose_name='جواب ادمین'),
        ),
    ]
